{% set name = "asyncua" %}
{% set version = "0.9.98" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f582bb98fdeaf964117a73447ec3ec6cd7ca872e90494212b19a047c940adc75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - uabrowse = asyncua.tools:uals
    - uacall = asyncua.tools:uacall
    - uaclient = asyncua.tools:uaclient
    - uadiscover = asyncua.tools:uadiscover
    - uageneratestructs = asyncua.tools:uageneratestructs
    - uahistoryread = asyncua.tools:uahistoryread
    - uals = asyncua.tools:uals
    - uaread = asyncua.tools:uaread
    - uaserver = asyncua.tools:uaserver
    - uasubscribe = asyncua.tools:uasubscribe
    - uawrite = asyncua.tools:uawrite

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiofiles
    - aiosqlite
    - cryptography
    - importlib-metadata
    - python >=3.7
    - python-dateutil
    - pytz
    - sortedcontainers

test:
  imports:
    - asyncua
  requires:
    - pip
  commands:
    - pip check
    - uabrowse --help
    - uacall --help
    - uaclient --help
    - uadiscover --help
    - uageneratestructs --help
    - uahistoryread --help
    - uals --help
    - uaread --help
    - uaserver --help
    - uasubscribe --help
    - uawrite --help


about:
  home: http://freeopcua.github.io
  summary: Pure Python OPC-UA client and server library
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING
  dev_url: https://github.com/FreeOpcUa/opcua-asyncio

extra:
  recipe-maintainers:
    - m-rossi
